import {
  BarChart3,
  TrendingUp,
  Bot,
  LayoutGrid,
  Activity,
  Zap,
} from "lucide-react";
import ProductCard from "@/components/ProductCard";
import DiagnosticsTable from "@/components/DiagnosticsTable";
import GettingStarted from "@/components/GettingStarted";
import { fallbackDiagnostics } from "@/data/diagnostics";

export default function Home() {
  const diagnosticCount = fallbackDiagnostics.length;

  return (
    <main className="mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:px-8">
      {/* ─── Hero ─── */}
      <section className="mb-20 text-center">
        <div className="mb-3 inline-flex items-center gap-1.5 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-3 py-1 text-xs font-medium text-indigo-300">
          <Activity className="h-3 w-3" />
          Agentic Customer Operations
        </div>

        <h1 className="mb-4 text-4xl font-bold tracking-tight text-white sm:text-5xl">
          Agentic Customer Operations
        </h1>
        <p className="mx-auto mb-10 max-w-2xl text-lg leading-relaxed text-slate-400">
          Three diagnostic products for customer operations transformation.
          Generate for any client using Cursor.
        </p>

        <div className="mx-auto grid max-w-xl grid-cols-3 gap-4">
          <StatCard icon={LayoutGrid} value="3" label="Products" />
          <StatCard
            icon={BarChart3}
            value={String(diagnosticCount)}
            label="Diagnostics Generated"
          />
          <StatCard icon={Zap} value="~20min" label="To Deploy" />
        </div>
      </section>

      {/* ─── Product Catalog ─── */}
      <section className="mb-20">
        <SectionHeading
          title="Product Catalog"
          subtitle="Each product is a complete, client-ready web app generated by Cursor from public data."
        />

        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          <ProductCard
            icon={BarChart3}
            title="NRR Diagnostic (Basic)"
            description="NRR benchmark vs peers, customer journey map with pain points, diagnostic synthesis with top strengths and risks to NRR."
            time="~15–30 min"
            exampleUrl="https://nrr-cx-okta.vercel.app/"
            accentColor="#10b981"
            badgeBg="rgba(16, 185, 129, 0.15)"
          />
          <ProductCard
            icon={TrendingUp}
            title="NRR Diagnostic (Enhanced)"
            description="Full deep-dive: NRR benchmark, maturity assessment, waterfall analysis, value-at-stake scenarios, highest-impact actions."
            time="~15–30 min"
            exampleUrl="https://nrr-cx-databricks-enhanced.vercel.app/"
            accentColor="#3b82f6"
            badgeBg="rgba(59, 130, 246, 0.15)"
          />
          <ProductCard
            icon={Bot}
            title="Customer Operations Assessment"
            description="Agentic AI readiness assessment for Customer Success, Professional Services, and Support. Role-by-role impact and transformation roadmap."
            time="~15–30 min"
            exampleUrl="https://oracle-ops-assessment.vercel.app/"
            accentColor="#a855f7"
            badgeBg="rgba(168, 85, 247, 0.15)"
          />
        </div>
      </section>

      {/* ─── Generated Diagnostics ─── */}
      <section className="mb-20">
        <SectionHeading
          title="Generated Diagnostics"
          subtitle="All diagnostics created by the team, sorted by date."
        />
        <DiagnosticsTable />
      </section>

      {/* ─── Getting Started ─── */}
      <section id="getting-started" className="mb-12">
        <SectionHeading
          title="How to Get Started"
          subtitle="Four steps from zero to a deployed, client-ready diagnostic."
        />
        <GettingStarted />
      </section>

      {/* ─── Footer ─── */}
      <footer className="border-t border-slate-800 pt-8 text-center text-xs text-slate-500">
        Agentic Customer Operations &middot; Built with Cursor &middot;
        Deployed on Vercel
      </footer>
    </main>
  );
}

/* ─── Shared sub-components ─── */

function StatCard({
  icon: Icon,
  value,
  label,
}: {
  icon: typeof BarChart3;
  value: string;
  label: string;
}) {
  return (
    <div className="rounded-xl border border-slate-700/60 bg-slate-800/40 px-4 py-4">
      <Icon className="mx-auto mb-2 h-5 w-5 text-indigo-400" />
      <div className="text-xl font-bold text-white">{value}</div>
      <div className="text-xs text-slate-400">{label}</div>
    </div>
  );
}

function SectionHeading({
  title,
  subtitle,
}: {
  title: string;
  subtitle: string;
}) {
  return (
    <div className="mb-8">
      <h2 className="mb-1.5 text-2xl font-bold text-white">{title}</h2>
      <p className="text-sm text-slate-400">{subtitle}</p>
    </div>
  );
}
